"""add base currency columns

Revision ID: 4248933cd0db
Revises: 626d9f1c4edc
Create Date: 2026-06-01 15:09:02.824322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = '4248933cd0db'
down_revision: Union[str, Sequence[str], None] = '626d9f1c4edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('symbol', sa.String(length=5), nullable=True, comment='e.g., €, $, £'))
    op.add_column('currencies', sa.Column('is_base', sa.Boolean(), nullable=True, comment="True if this is the user's primary/home currency"))
    # ### end Alembic commands ###

    currencies_table = table('currencies',
                             column('code', sa.String),
                             column('symbol', sa.String),
                             column('is_base', sa.Boolean)
                             )

    op.execute(
        currencies_table.update().where(
            currencies_table.c.code == 'EUR'
        ).values(
            is_base=True,
            symbol='€'
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currencies', 'is_base')
    op.drop_column('currencies', 'symbol')
    # ### end Alembic commands ###
