"""Add quotation_method, decimals, increased code max length from 3 to 10

Revision ID: e6618a898bef
Revises: 4248933cd0db
Create Date: 2026-06-15 16:24:32.360357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6618a898bef'
down_revision: Union[str, Sequence[str], None] = '4248933cd0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quotation_method', sa.String(length=10), nullable=True, comment="For conversion purposes - 'multiply' or 'divide'"))
        batch_op.add_column(sa.Column('decimals', sa.Integer(), nullable=True, comment='Number of decimals: 0 for JPY, 2 for USD, etc.'))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
        batch_op.drop_column('decimals')
        batch_op.drop_column('quotation_method')

    # ### end Alembic commands ###
